name: sp1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  flutter_tts: ^3.8.3
  http: ^1.1.0

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  avatar_glow: ^3.0.1
  google_ml_kit: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # âœ… Assets added here
  assets:
    - assets/data/schemes.json